### ISSUE TITLE
Видео обзор библиотеки?

### ISSUE THREAD

**Issue by paantya** [sberbank-ai-lab/LightAutoML#10]
На ai-journey, вроде был обзор, но сейчас не могу его найти, помогите пожалуйста найти видео
Оно было бы очень уместно и было бы здорово добавить его на главную станицу либы, как альтернативу ноутбукам

**Comment by alexmryzhkov** [comment]
Hi @paantya! Both general overview and practical video guide are in the first section of our readme file. The record from our AIJourney workshop is currently unavailable but we are working on it :)

**Comment by paantya** [comment]
Cool!
Tnx,I hope everything will work out with the video

**Comment by alexmryzhkov** [comment]
Hi @paantya, we have good news for you - the new 3h deep dive into LightAutoML released: https://youtu.be/ci8uqgWFJGg
