### ISSUE TITLE
ColumnSelector - possible typing typo

### ISSUE THREAD

**Issue by se-teryoshkin** [sberbank-ai-lab/LightAutoML#108]
https://github.com/sberbank-ai-lab/LightAutoML/blob/master/lightautoml/transformers/base.py#L368

I suppose in this method signature should be LAMLDataset instead of LAMLTransformer.

**Comment by alexmryzhkov** [comment]
@se-teryoshkin yep, you are right - will fix the typo this evening.

P.S. Would you like to work with us full-time on the LightAutoML framework? If yes, you can share your CV with me in Telegram @RyzhkovAlex :)
