### ISSUE TITLE
colab crashing for unknown reason

### ISSUE THREAD

**Issue by nitishsantpur** [sberbank-ai-lab/LightAutoML#127]
Google colab crashes with unknown reasons 
It was running fine up until 2 days earlier 
It stops during model training 
![w1](https://user-images.githubusercontent.com/71618329/159897880-c2d7a58e-10d7-44f2-9979-03284e0ed761.PNG)
![w2](https://user-images.githubusercontent.com/71618329/159897911-3b35ba0e-89db-454a-af79-c0906060d1cc.PNG)
![s1](https://user-images.githubusercontent.com/71618329/159897942-8fa61f60-d8b4-4424-9184-84e00029db4c.PNG)
![s2](https://user-images.githubusercontent.com/71618329/159897966-59fd4ef2-10e2-4d76-b60e-1f083039403d.PNG)
It would be really helpful if someone can resolve this issue, I ve checked on multiple forums but got no satisfactory results

**Comment by alexmryzhkov** [comment]
Hi @nitishsantpur,

I have checked our tutorial_1 in colab and everything works fine, so I think there is a problem with your colab env. Could you please try to do the same in the new env or on your desktop PC to check?

Alex

**Comment by nitishsantpur** [comment]
Hi I have tried it on different machine it crashes while catboost in tabularautoml 
![Capture](https://user-images.githubusercontent.com/71618329/159961168-824189fb-f2d6-4477-b4e9-208a7db37d50.PNG)
![Capture1](https://user-images.githubusercontent.com/71618329/159961207-fbf7ed7c-38d3-45d5-98b6-4c6c7ba71d17.PNG)

**Comment by alexmryzhkov** [comment]
Hi @nitishsantpur,

I have looked on your colab notebook - haven't seen any specific problems. 
What you can check to figure out:
1) Try to set one more param for TabularAutoML - the code can be like this:
`general_params = {'use_algos': [['linear_l2', 'lgb', 'lgb_tuned']]}`
2) Please check your memory usage during the catboost fit - maybe it is simple memory error

Alex

**Comment by nitishsantpur** [comment]
Ya I tried using general_params = {'use_algos': [['linear_l2', 'lgb', 'lgb_tuned']]} and it worked my RAM and disk seems to be low that it why it takes time while catboost

**Comment by alexmryzhkov** [comment]
@nitishsantpur great that it works. As for catboost - it is pretty slow on CPU by default and has higher speed on GPU due to the implementation by its developers
