### ISSUE TITLE
OSError on MacOs

### ISSUE THREAD

**Issue by koteyevlev** [sberbank-ai-lab/LightAutoML#21]
After successful installation, it throws this error when trying to import the library on Mac Os python 3.8. How can I fix this?

OSError                                   Traceback (most recent call last)
<ipython-input-5-362a05de38e5> in <module>
     20 from sklearn.linear_model import LinearRegression, LogisticRegression
     21 from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
---> 22 import lightautoml
     23 from lightautoml.automl.presets.tabular_presets import TabularAutoML
     24 from lightautoml.tasks import Task

~/.local/lib/python3.8/site-packages/lightautoml/__init__.py in <module>
     14     __version__ = importlib_metadata.version(__name__)
     15 
---> 16     from .addons import *
     17     from .addons.utilization import *
     18     from .automl import *

~/.local/lib/python3.8/site-packages/lightautoml/addons/utilization/__init__.py in <module>
      1 """Tools to configure resources utilization."""
----> 2 from .utilization import TimeUtilization
      3 
      4 __all__ = ['TimeUtilization']

~/.local/lib/python3.8/site-packages/lightautoml/addons/utilization/utilization.py in <module>
      6 from log_calls import record_history
      7 
----> 8 from ...automl.base import AutoML
      9 from ...automl.blend import Blender, BestModelSelector
     10 from ...automl.presets.base import AutoMLPreset

~/.local/lib/python3.8/site-packages/lightautoml/automl/base.py in <module>
      6 from log_calls import record_history
      7 
----> 8 from .blend import Blender, BestModelSelector
      9 from ..dataset.base import LAMLDataset
     10 from ..dataset.utils import concatenate

~/.local/lib/python3.8/site-packages/lightautoml/automl/blend.py in <module>
      7 from scipy.optimize import minimize_scalar
      8 
----> 9 from ..dataset.base import LAMLDataset
     10 from ..dataset.np_pd_dataset import NumpyDataset
     11 from ..dataset.roles import NumericRole

~/.local/lib/python3.8/site-packages/lightautoml/dataset/base.py in <module>
      7 
      8 from .roles import ColumnRole
----> 9 from ..tasks.base import Task
     10 
     11 valid_array_attributes = ('target', 'group', 'folds', 'weights')

~/.local/lib/python3.8/site-packages/lightautoml/tasks/__init__.py in <module>
      1 """Define the task to solve its loss, metric."""
      2 
----> 3 from .base import Task
      4 
      5 __all__ = ['losses', 'base', 'common_metric', 'utils', 'Task']

~/.local/lib/python3.8/site-packages/lightautoml/tasks/base.py in <module>
      8 from log_calls import record_history
      9 
---> 10 from lightautoml.tasks.losses import LGBLoss, SKLoss, TORCHLoss, CBLoss
     11 from .common_metric import _valid_str_metric_names, _valid_metric_args
     12 from .utils import infer_gib, infer_gib_multiclass

~/.local/lib/python3.8/site-packages/lightautoml/tasks/losses/__init__.py in <module>
      3 from .base import _valid_str_metric_names
      4 from .cb import CBLoss
----> 5 from .lgb import LGBLoss
      6 from .sklearn import SKLoss
      7 from .torch import TORCHLoss, TorchLossWrapper

~/.local/lib/python3.8/site-packages/lightautoml/tasks/losses/lgb.py in <module>
      4 from typing import Callable, Tuple, Union, Optional, Dict
      5 
----> 6 import lightgbm as lgb
      7 import numpy as np
      8 from log_calls import record_history

~/.local/lib/python3.8/site-packages/lightgbm/__init__.py in <module>
      6 from __future__ import absolute_import
      7 
----> 8 from .basic import Booster, Dataset
      9 from .callback import (early_stopping, print_evaluation, record_evaluation,
     10                        reset_parameter)

~/.local/lib/python3.8/site-packages/lightgbm/basic.py in <module>
     31 
     32 
---> 33 _LIB = _load_lib()
     34 
     35 

~/.local/lib/python3.8/site-packages/lightgbm/basic.py in _load_lib()
     26     if len(lib_path) == 0:
     27         return None
---> 28     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     29     lib.LGBM_GetLastError.restype = ctypes.c_char_p
     30     return lib

/Library/anaconda3/lib/python3.8/ctypes/__init__.py in LoadLibrary(self, name)
    449 
    450     def LoadLibrary(self, name):
--> 451         return self._dlltype(name)
    452 
    453 cdll = LibraryLoader(CDLL)

/Library/anaconda3/lib/python3.8/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    371 
    372         if handle is None:
--> 373             self._handle = _dlopen(self._name, mode)
    374         else:
    375             self._handle = handle

OSError: dlopen(/Users/a185583357/.local/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/a185583357/.local/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found

**Comment by alexeytomashyov** [comment]
I encountered the same problem (see Issue #5) and was proposed to try `brew install libomp`. It worked for me.

**Comment by koteyevlev** [comment]
Thanks for help!
