### ISSUE TITLE
Incorrect gensim.models.FastText usage

### ISSUE THREAD

**Issue by VladVin** [sberbank-ai-lab/LightAutoML#31]
The library looks great, thank you for the work. But I had an issue running TabularNLPAutoML.
You use an arbitrary version of gensim setting `gensim = "*"` in the dependencies [here](https://github.com/sberbank-ai-lab/LightAutoML/blob/master/pyproject.toml#L52). It leads to using any version of gensim including 4.* where parameter `size` of `gensim.models.FastText` class [was renamed](https://radimrehurek.com/gensim/models/fasttext.html) in favour of `vector_size`. This causes a failure running `TabularNLPAutoML`. Overall, consider fixed versions of dependencies for not having such issues all the time.

**Comment by sakutepov** [comment]
Faced with a similar situation.
Worked for me: pip install -U gensim == 3.8.3

**Comment by CrustaceanJ** [comment]
Good evening, @VladVin! Thank you for the comment.

Sorry for the late response. In last build, we migrated to ``gensim >=4``.
