### ISSUE TITLE
Space error in a Virtual Environment/Machine?

### ISSUE THREAD

**Issue by shravankoninti** [sberbank-ai-lab/LightAutoML#34]
Hi Team,
Question on installing this lightAutoML:

I am trying to use this installation in a specific environment or machine where the space is low. Can we customize to the installations related to only multiclass problem only (non-NLP data)? I really do not want any installations of NLP/Image processing, may be these are taking lot of space. How can I customize my installations according to problem? In this case I want to use only lightgbm/catboost hyper tuned stuff only.

![image](https://user-images.githubusercontent.com/6191291/118608608-7ee94300-b7d7-11eb-849c-a40762274c73.png)

![image](https://user-images.githubusercontent.com/6191291/118608492-61b47480-b7d7-11eb-8a4e-02c045a76743.png)

Regards
Shravan

**Comment by alexmryzhkov** [comment]
Hello, @shravankoninti!

Firstly, sorry for late reply. 

To create models in LightAutoML we use torch as we have linear models based on it (it's much faster than sklearn variant). 

Currently we don't have any installation options but we'll think about them in the future releases.

Alex
