### ISSUE TITLE
Inquiring about model saving feature 

### ISSUE THREAD

**Issue by bamblebam** [sberbank-ai-lab/LightAutoML#37]
So I just trained a model on some tabular data using TabularUtilizedAutoML and wanted to save the model. But I couldn't find anything related to saving the best trained model.  
Just wanted to know if there is a functionality to do so ?

**Comment by alexmryzhkov** [comment]
Hi @bamblebam,

The best trained model is already inside automl object, which you can use to do prediction for the test data. 

If you want to save the the model, you can use `joblib` library: `joblib.dump(automl, 'trained_lightautoml_model.pkl')` 
To load the model the code `automl = joblib.load('trained_lightautoml_model.pkl')` can be used.

Hope this helps.

Alex

**Comment by bamblebam** [comment]
Thank You for replying.
