### ISSUE TITLE
ReportDeco does not work on all the AutoML objects

### ISSUE THREAD

**Issue by rozlana-g** [sberbank-ai-lab/LightAutoML#47]
I can not wrap AutoML from the tutorial into ReportDeco wrapper in [ Tutorial 3](https://colab.research.google.com/github/sberbank-ai-lab/LightAutoML/blob/master/Tutorial_3.%20Multiclass%20task.ipynb#scrollTo=ql6OAdRpXEdv).

After 
```python
automl = AutoML(reader=reader, levels=[
    [gbm_lvl0, reg_lvl0]
], timer=timer, blender=blender, skip_conn=False)
```
adding
```python
from lightautoml.report import ReportDeco
RD = ReportDeco(output_path='./binary_report/')
automl = RD(automl)

```
gives error 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-7df350cbcb2a> in <module>()
      1 from lightautoml.report import ReportDeco
      2 RD = ReportDeco(output_path='./binary_report/')
----> 3 automl = RD(automl)

/usr/local/lib/python3.7/dist-packages/lightautoml/report/report_deco.py in __call__(self, model)
    375 
    376         # AutoML only
--> 377         self.task = self._model.task._name  # valid_task_names = ['binary', 'reg', 'multiclass']
    378 
    379         # add informataion to report

AttributeError: 'AutoML' object has no attribute 'task'
```

Looks like ReportDeco works only with tabular preset.

**Comment by VaBun** [comment]
Hi, @rozlana-g,

Thank you for detailed description of the problem. `ReportDeco` now works with base class `AutoML`. The corrected version is already available on GitHub, and soon will be added to `pip`.

**Comment by alexmryzhkov** [comment]
Hi @rozlana-g,

I hope that everything should be alright and we are going with these changes from @VaBun to create new version for pip. If something goes wrong - please reopen this issue.

Alex
