### ISSUE TITLE
[Request] Release notes

### ISSUE THREAD

**Issue by PGijsbers** [sberbank-ai-lab/LightAutoML#54]
As far as I can tell, there are no release notes for the different releases. I want to suggest starting with release notes for new releases. At least I myself was trying to figure out if a particular property changed between releases, and found myself with no way to figure that out (other than empirically trying both versions).

**Comment by alexmryzhkov** [comment]
Hi @PGijsbers,

Thanks for cool idea - we had them in our Telegram channel in russian, but I'm also going to post them here in releases tab :)

Alex

**Comment by PGijsbers** [comment]
Feel free to close the issue now, or whenever you add your first release notes :)

**Comment by alexmryzhkov** [comment]
Here they are:

**Release notes for 0.2.11**:
- Added variable importances calculation functions for `TabularAutoML` and `TabularUtilizedAutoML` - example is in `Tutorial_2`.
- Added new functionality to return predictions from all algorithms before the blender layer for Train (OOF preds) and Prediction (Test preds) stages. To do that you can use `return_all_predictions` and `weighted_blender_max_nonzero_coef` params in `general_params` config section, [example is here in cell 9](https://www.kaggle.com/alexryzhkov/lightautoml-baseline-tps-june-2021)
- Bug-fixes for custom metrics and `TabularUtilizedAutoML` custom config list setting (for example to make it work like model multistart) etc.

---

**Release notes for 0.2.12**:
- Added classififcation NLP models interpretation based on LIME. 
- Better support for HuggingFace models for embeddings training and extraction.
- Bug-fixes for language argument in several embeddings extraction algos and tokenizers

---

**Release notes for 0.2.13**:
- Added regression NLP models interpretation based on LIME.

---

**Release notes for 0.2.14-0.2.15**:
- Bug-fixes based on user reviews in the core functionality and report generation.

---

**Release notes for 0.2.16**:
__General part__:
- Removing profiler functionality (`log_calls` library usage) makes available to use `DataParallel` during Bert models training (to turn it on use `multigpu` param in `nn_params`)

__NLP part__: 
- Migration to `gensim >=4`.
- Added functionaly to force big NLP models calculation without GPU (Random LSTM, Pooled Bert, etc).
- Changed logic of default parameters selection process: removing NN from pipeline if no GPU available, language and Bert model propagates to `AutoNLP` and `NN` via `text_params`, changed logic for embeddings size check in `AutoNLP`
- Added several normalization techniques for embeddings in `AutoNLP` module

__Interpretation part__:
- Minor changes in LIME part - now we can show AutoML prediction and the predictions scale colorbar.
- L2X local interpretation algorithm is now available for NLP models. It finds the most informative tokens for the target variable based on the AutoML model predictions by mutual information optimization. For more info please check [this tutorial in the repo](https://github.com/sberbank-ai-lab/LightAutoML/blob/master/Tutorial_5.%20NLP%20Interpretation.ipynb) or [the same in the nbviewer](https://nbviewer.jupyter.org/github/sberbank-ai-lab/LightAutoML/blob/pooling_fix/Tutorial_5.%20NLP%20Interpretation.ipynb)
