### ISSUE TITLE
save model

### ISSUE THREAD

**Issue by lk137095576** [sberbank-ai-lab/LightAutoML#55]
how to save and load  model config or weight?

**Comment by alexmryzhkov** [comment]
Hi @lk137095576,
To save the model you can use `joblib.dump(automl, ‘model.pkl’)`.
To load the model you can use
`automl=joblib.load(‘model.pkl’)`

Both these commands need `import joblib` at the begging of the script.

Alex

**Comment by lk137095576** [comment]
> Hi @lk137095576,
> To save the model you can use `joblib.dump(automl, ‘model.pkl’)`.
> To load the model you can use
> `automl=joblib.load(‘model.pkl’)`
> 
> Both these commands need `import joblib` at the begging of the script.
> 
> Alex

thx
