### ISSUE TITLE
ERROR: torch has an invalid wheel, .dist-info directory not found

### ISSUE THREAD

**Issue by georsara1** [sberbank-ai-lab/LightAutoML#7]
I am getting this error while trying to pip install in a windows machine. Pip version is 20.0.2

"ERROR: torch has an invalid wheel, .dist-info directory not found"

**Comment by alexmryzhkov** [comment]
Hi @georsara1! 

For windows it's a little bit more complicated to install LAMA - could you please try to install torch beforehand into your environment and install LAMA via pip after that?

Alex

**Comment by selfcontrol7** [comment]
> I am getting this error while trying to pip install in a windows machine. Pip version is 20.0.2
> 
> "ERROR: torch has an invalid wheel, .dist-info directory not found"

Hello, just in case it can help, I face the same error and proceed with the following commands: 

If you do not need a CUDA installation
`pip install torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

If you fo need a CUDA installation
`pip install torch===1.7.0 torchvision===0.8.1 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

More details about the CUDA version on the official [website](https://pytorch.org/get-started/locally/)

Hope it helps.

**Comment by georsara1** [comment]
Selfcontrol7's answer worked for me. No GPU on my laptop so I went for the NO CUDA installation first and re-tried to pip install LAMA afterwards. That did the trick, thanks Selfcontrol7!

**Comment by georsara1** [comment]
See Selfcontrol7's answer
