### ISSUE TITLE
Issue with "Tutorial_1. Create your own pipeline.ipynb"

### ISSUE THREAD

**Issue by Godofnothing** [sberbank-ai-lab/LightAutoML#71]
Hi! 

When running the first tutorial on `Google.Colab` from the colab button in `README.md` I've faced the following issue in the import of `lightautoml`:

`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

I've found a solution [here](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp) in the first answer. But it seems that the notebook should be updated.

**Comment by ledovsky** [comment]
+1

**Comment by dev-rinchin** [comment]
Hi!

There really is such a problem with Numpy for Python >= 3.7. We've fixed it, but haven't released it yet:
https://github.com/sberbank-ai-lab/LightAutoML/blob/master/pyproject.toml#L31

The new release will be coming soon, thanks for the report!

**Comment by dev-rinchin** [comment]
@Godofnothing you can update Numpy to version >=1.2.0 for fast fix :)
```
pip install numpy>=1.2.0
```
