### ISSUE TITLE
The kernel appears to have died

### ISSUE THREAD

**Issue by Vitaliy31** [sberbank-ai-lab/LightAutoML#73]
Hi!

When linear_l2 ends and lgb starts the kernel dies. 
Tried updating libraries, nothing worked. Dataset size seems to be ok, about 30k observations and 10 columns 
Using Jupyter on Mac OS.

Thanks!

**Comment by alexmryzhkov** [comment]
Hi @Vitaliy31,

Thanks for the feedback. Could you please share the train log you receive before the kernel dies and (if possible) the Ipynb file? This info will help us to find the issue faster.

Thanks in advance.

Alex

**Comment by Vitaliy31** [comment]
Sure!

[Car Price 1.ipynb.zip](https://github.com/sberbank-ai-lab/LightAutoML/files/7156651/Car.Price.1.ipynb.zip)

And the train log is below
```
Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed
Time left 576.231377363205
Start fitting Selector_LightGBM ...

===== Start working with fold 0 for Selector_LightGBM =====

Training until validation scores don't improve for 200 rounds
[100]	valid's l1: 2114.08
[200]	valid's l1: 1960.2
[300]	valid's l1: 1901.21
[400]	valid's l1: 1868.39
[500]	valid's l1: 1839.31
[600]	valid's l1: 1817.48
[700]	valid's l1: 1796.82
[800]	valid's l1: 1782.05
[900]	valid's l1: 1771.27
[1000]	valid's l1: 1763.77
[1100]	valid's l1: 1752
[1200]	valid's l1: 1744.96
Did not meet early stopping. Best iteration is:
[1200]	valid's l1: 1744.96
Selector_LightGBM fitting and predicting completed
```

**Comment by alexmryzhkov** [comment]
@Vitaliy31,

Thanks! Have tried your code on Ubuntu and MacOS - everything works fine. As I can see you have worked on MacOS - for me it was python 3.7. Could you share your python version and package versions?

Could you also check the jupyter console during the kernel crash - the stack trace can be there...

Alex

**Comment by Vitaliy31** [comment]
@alexmryzhkov , 

I use Python 3.9 and the following packages versions
lightautoml 0.2.16
numpy 1.20.1
pandas 1.2.4
torch 1.8.1
lightgbm 3.2.1

the Jupiter console just says
```
KernelRestarter: restarting kernel (1/5), keep random ports
kernel 36186ccd-6689-4ce8-a7a2-79f6139fbf7a restarted
```

**Comment by alexmryzhkov** [comment]
@Vitaliy31 That's sounds really interesting - I have tried your notebook on python 3.9 inside the kernel created using the commands (and it works fine):
```
conda create -n new_py39  python=3.9
conda activate new_py39
pip install -U pip
pip install -U jupyter ipython
pip install -U lightautoml
pip install -U ipykernel
python -m ipykernel install --name py39-new
jupyter notebook
```

I have also appended the requirements.txt file with the versions for all packages
[requirements.txt](https://github.com/sberbank-ai-lab/LightAutoML/files/7195104/requirements.txt).

For the packages you have stated in your message comparing to my env:
- lightautoml 0.2.16
- numpy 1.21.2
- pandas 1.3.3
- torch 1.8.1
- lightgbm 2.3.1 (the major difference between the envs is here - I will investigate more on that)

Alex

**Comment by alexmryzhkov** [comment]
Hi @Vitaliy31,

Have you tried the described above way for env creation? If you still faced the same issue please let me know and reopen this issue.

Alex
