### ISSUE TITLE
Problem with create_model_str_desc

### ISSUE THREAD

**Issue by brut0** [sberbank-ai-lab/LightAutoML#77]
I tried to get model parameters using `create_model_str_desc()` but got this error: `AttributeError: 'TabularAutoML' object has no attribute 'create_model_str_desc'`
I use this notebook as example: https://www.kaggle.com/alexryzhkov/aug21-lightautoml-starter

**Comment by alexmryzhkov** [comment]
Hi @brut0,

This is currently the intended behaviour - in the notebook you refer it was the developers version of LightAutoML which was installed from the specific github repo branch. Currently this function is inside master but not in PyPI yet - we are working on that and will make the new release soon.

Alex
