### ISSUE TITLE
 Error while import in docker image ubi8 (redhat)

### ISSUE THREAD

**Issue by Maksim-Vatkin** [sberbank-ai-lab/LightAutoML#80]
I've got the issue while using lightautoml inside docker image build on base image ubi8. 
The command
import lightautoml
lead to error (see a screenshot)
![image](https://user-images.githubusercontent.com/11646889/135467057-f00d8792-c533-4ea3-8ffe-b376e9e1630c.png)

**Comment by PhySci** [comment]
@Maksim-Vatkin I suspect not all requirements have been installed into the docker image. It's a common problem when  minimal base images are being used (alpine or ubi8).
  I would suggest to run the image (docker run ...), connect to it (docker exec ...), open python console and try to import CV2 package. If you couldn't do it, it means that the source of problem isn't LightAutoML, but missing dependencies of the CV2.

**Comment by alexmryzhkov** [comment]
Hello @Maksim-Vatkin @PhySci,

As we discussed in the private messages with @Maksim-Vatkin, the working configuration for this case is:
```
FROM registry.access.redhat.com/ubi8/python-38

RUN pip3 install --upgrade pip
RUN pip3 install lightautoml
RUN pip3 install --force-reinstall opencv-python-headless

ENTRYPOINT ["bash", "-c"]
CMD ["echo 'Needs executable to be passed as argument'"]
```

I'll close the issue for now but if the solution doesn't work for your case please re-open the issue.

Alex
