### ISSUE TITLE
Poetry cant solve deps

### ISSUE THREAD

**Issue by avmartugin** [sberbank-ai-lab/LightAutoML#92]
poetry 1.1.11 cant solve deps for lightautoml==0.3.0 and python 3.9.5

poetry update
Creating virtualenv test1-xVJJlKZl-py3.9 in /home/user/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  The current project's Python requirement (>=3.9,<4.0) is not compatible with some of the required packages Python requirement:
    - lightautoml requires Python >=3.6.1,<3.10, so it will not be satisfied for Python >=3.10,<4.0
  
  Because no versions of lightautoml match >0.3.0,<0.4.0
   and lightautoml (0.3.0) requires Python >=3.6.1,<3.10, lightautoml is forbidden.
  So, because test1 depends on lightautoml (^0.3.0), version solving failed.

  at ~/.local/lib/python3.9/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For lightautoml, a possible solution would be to set the `python` property to ">=3.9,<3.10"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers

**Comment by JDonini** [comment]
[tool.poetry.dependencies]
python = ">=3.7, <3.10" or python = "~3.9"
